### ISSUE TITLE
Whether to support the latest version of django2.0 xadmin

### ISSUE THREAD

**Issue by hequan2017** [alexsilva/xadmin.plugin.guardian#1]
Whether to support the latest version of django2.0 xadmin

**Comment by hequan2017** [comment]
After my test, found that are not compatible

**Comment by alexsilva** [comment]
I'm developing with Django 1.9. You can make a fork and make the port for version 2.0 (django and xadmin).

**Comment by alexsilva** [comment]
It is now supported: https://github.com/alexsilva/xadmin-guardian-plugin/tree/bs4_dj2
